export { userRoleEnum, users } from './users.js'
export { aiActionTypeEnum, aiLogs, aiLogsRelations } from './domain.js'
export {
  patients,
  healthProfessionals,
  specialties,
  workingHours,
  appointments,
  appointmentStatusEnum,
  appointmentCancelledByEnum,
  telemedicineRoomStatusEnum,
  notificationStatusEnum,
  notificationTypeEnum,
  documentTypeEnum,
  medicalRecords,
  diagnoses,
  prescriptions,
  telemedicineRooms,
  telemedicineMessages,
  documents,
  notifications,
  emotionLogs,
  professionalPatients,
  reports,
  appointmentMessages,
  // Relations – required for db.query.*.findFirst({ with: ... })
  usersRelations,
  patientsRelations,
  healthProfessionalsRelations,
  specialtiesRelations,
  workingHoursRelations,
  appointmentsRelations,
  appointmentMessagesRelations,
  medicalRecordsRelations,
  diagnosesRelations,
  prescriptionsRelations,
  documentsRelations,
  notificationsRelations,
  telemedicineRoomsRelations,
  telemedicineMessagesRelations,
  emotionLogsRelations,
  professionalPatientsRelations,
  reportsRelations,
} from './domain.js'
